name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with HTML report
      run: |
        pytest --html=pytest_report.html

    - name: Upload Pytest HTML report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: pytest_report.html

  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8 with HTML report
      run: |
        flake8 . --format=html --htmldir=flake8_report

    - name: Upload Flake8 HTML report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8_report
